package vn.edu.hcmute.bookstore.controller;
import jakarta.servlet.*;import jakarta.servlet.annotation.WebServlet;import jakarta.servlet.http.*;import vn.edu.hcmute.bookstore.model.Author_24110171;import vn.edu.hcmute.bookstore.service.AuthorService_24110171;import vn.edu.hcmute.bookstore.util.WebUtil_24110171;import java.io.IOException;import java.time.LocalDate;
@WebServlet("/admin/authors/*")
public class AdminAuthorController_24110171 extends HttpServlet{
    private final AuthorService_24110171 authors=new AuthorService_24110171();private static final int SIZE=6;
    protected void doGet(HttpServletRequest req,HttpServletResponse resp)throws ServletException,IOException{String p=req.getPathInfo()==null?"/":req.getPathInfo();if("/create".equals(p)){show(req,resp,new Author_24110171());return;}if("/edit".equals(p)){Author_24110171 a=authors.find(WebUtil_24110171.intParam(req,"id",0));if(a==null){resp.sendError(404);return;}show(req,resp,a);return;}if("/delete".equals(p)){try{authors.delete(WebUtil_24110171.intParam(req,"id",0));req.getSession().setAttribute("adminMsg","Đã xóa tác giả.");}catch(Exception e){req.getSession().setAttribute("adminMsg","Không xóa được tác giả vì đang được gán cho sách.");}resp.sendRedirect(req.getContextPath()+"/admin/authors");return;}int page=Math.max(1,WebUtil_24110171.intParam(req,"page",1));req.setAttribute("authors",authors.page(page,SIZE));req.setAttribute("page",page);req.setAttribute("totalPages",authors.totalPages(SIZE));req.getRequestDispatcher("/WEB-INF/views/admin/authors/list.jsp").forward(req,resp);}
    protected void doPost(HttpServletRequest req,HttpServletResponse resp)throws IOException{req.setCharacterEncoding("UTF-8");int id=WebUtil_24110171.intParam(req,"id",0);Author_24110171 a=id>0?authors.find(id):new Author_24110171();if(a==null)a=new Author_24110171();a.setAuthorName(WebUtil_24110171.trim(req.getParameter("authorName")));try{a.setDateOfBirth(LocalDate.parse(req.getParameter("dateOfBirth")));}catch(Exception e){a.setDateOfBirth(null);}if(id>0)authors.update(a);else authors.save(a);req.getSession().setAttribute("adminMsg",id>0?"Đã cập nhật tác giả.":"Đã thêm tác giả.");resp.sendRedirect(req.getContextPath()+"/admin/authors");}
    private void show(HttpServletRequest req,HttpServletResponse resp,Author_24110171 a)throws ServletException,IOException{req.setAttribute("author",a);req.getRequestDispatcher("/WEB-INF/views/admin/authors/form.jsp").forward(req,resp);}
}
