
db.url=jdbc:sqlserver://localhost:1433;databaseName=BookStore_24110171;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
db.user=sa
db.password=chien722006
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.dialect=org.hibernate.dialect.SQLServerDialect
hibernate.hbm2ddl.auto=none
